import { post } from "axios";
import MainMenu from "../screens/main_menu";
import FavouriteMealsScreen from "../screens/favourites";
import PaymentScreen from "../screens/payment";
import { fetchDiscounts } from "../discount";

export default {
  login: {
    title: 'Login',
    anonymous: 'Anonymous mode',
    register: 'Register',
    appName: 'At the Blind Eagle',
    name: 'Name',
    password: 'Password',
    rememberMe: 'Remember me',
    loginButton: 'Log in',
    loginFailed: 'Login failed',
    connectionFailed: 'Connection failed',
    offlineModeMessage: 'Using offline mode, limited functionality...'
  },
  account: {
    pubName: "At the Blind Eagle",
    login: "Login",
    register: "Register",
    anonymous: "Anonymous mode",
    discount: "Discount",
    logout: "Logout",
    darkMode: "Dark mode",
    language: "Language",
    accessibility: "Accessibility",
    fontSize: "Font size",
    highContrast: "High contrast",
    setting1: "Setting 1",
    setting2: "Setting 2",
    setting3: "Setting 3",
    changePassword: "Change Password",
    myReservations: "My Reservations",
    save: "Save changes",
    loyality_points: "Actual loyalty points",
    fav_meals: "Free spaces for favourite meals",
    loyality_discount: "Maximal discount from loyalty points",
    loyality_level: "Loyalty level",

  },
  changePassword: {
    title: 'Change Password',
    old: 'Old Password',
    new: 'New Password',
    confirm: 'Confirm New Password',
    save: 'Change Password',
    success: 'Password successfully changed.',
    errorMismatch: 'New passwords do not match.',
    errorEmpty: 'Please fill in all required fields.',
    errorAnon: 'Anonymous users cannot change password.',
    errorServer: 'Failed to connect to server.',
    errorUnknown: 'Failed to change password.',
    saving: 'Saving...',
  },
  MainMenu:{
    today_special: "Today's Special",
    categories: "Categories",
    your_space: "Your Space",
    menu: "Menu",
    search: "Search",
    admin_only: "Admin only",
    unauthorized: "Unauthorized access"
  },
  DeliveryScreen: {
    delivery: "Delivery",
    reservation: "Reservation",
    street: "Street",
    number: "Number",
    postal_code: "Postal Code",
    order_now: "Order Now",
    comment: "Comment",
    date: "Choose Date",
    time_from: "time from",
    time_to: "time until",
    pay: "Pay",
    number_of_people: "Number of Guests",
    track_order: "Track Order",
    delivery_time: "Estimated Delivery Time",
    address: "Delivery Address",
    change_address: "Change Address",
    delivery_options: "Delivery Options or Reservation",
    cancel: "Cancel Order",
    status_preparing: "Preparing your order...",
    status_out_for_delivery: "Out for delivery",
    status_delivered: "Delivered",
    error_invalid_address: "Please enter a valid address.",
    error_no_connection: "No connection. Please try again.",
    success_confirmed: "Your delivery has been confirmed.",
    success_cancelled: "Your delivery has been cancelled."
  },
    LoyalityScreen: {
    title: "Loyalty Program",
    points: "Points",
    rewards: "Rewards",
    discount: "Discount",
    currentDiscount: "Current Discount",
    skipButton: "Skip",
    loading: "The incorrect data read. Try again after account verification."
  },

    RegisterScreen: {
      register: "Register",
      password_again: "Re-enter Password",
    },

    AddItemScreen:  {
        dish_title: "Dish Title:",
        dish_image: "Dish Item:",
        category: "Category:",
        description: "Description:",
        portion_size: "Portion Sizes:",
        unit: "Portion Unit:",
        discount: "Discount Base:",
        special: "Today's Special:",
        cancel: "Cancel",
        addButton: "Add item",
        small: "Small",
        medium: "Medium",
        large: "Large",
        delete: "Delete",
        save: "Save",
        unit2: "Unit (g/ml):",
        discount2: "Discount %:",
        size: "Size:",
        price: "Price:",
        error: "Error",
        category2: "Enter category",
        title2: "Enter dish title",
        desc2: "Enter description",
        unit3: "Enter portion unit (g/ml)",
    },

    FavouriteMealsScreen: {
      title: "Favourites",
    },

    PaymentScreen: {
      title: "Payment",
      with_card: "Pay with card",
      after_delivery: "Pay after delivery",
      card: "Card details",
      card_number: "Card Number",
      card_expiry: "Expiry Date (MM/YY)",
      card_cvc: "CVC",
      number_of_items: "Number of items",
      total_price: "Total Price",
      discount: "Discount",
      pay: "Pay",
      confirm: "Your confirmation:",
      total: "Total",
      delivery_price: "Delivery: 2.50 €",
      reservation_price: "Reservation: 1.50 €",
    },
    add_to_cart: "Add to cart",

    ShoppingCartScreen: {
      title: "Shopping Cart",
      empty: "Your cart is empty.",
      total_price: "Total Price",
      total_items: "Total Items",
      remove_item: "Remove Item",
      checkout: "Checkout",
      continue_shopping: "Continue Shopping",
      item_removed: "Item removed from cart.",
      item_added: "Item added to cart.",
      error: "Error",
      order: "Order",
    },
};