import FavouriteMealsScreen from "../screens/favourites";
import ShoppingCartScreen from "../screens/shopping_cart";

export default {
    login: {
      appName: 'У Слепого Орла',
      name: 'Имя',
      password: 'Пароль',
      rememberMe: 'Запомнить меня',
      loginButton: 'Войти',
      loginFailed: 'Ошибка входа',
      connectionFailed: 'Ошибка подключения',
      offlineModeMessage: 'Используется автономный режим...'
    },
    account: {
        pubName: "У слепого орла",
        login: "Войти",
        register: "Зарегистрироваться",
        anonymous: "Анонимный режим",
        discount: "Скидка",
        logout: "Выйти",
        darkMode: "Тёмный режим",
        language: "Язык",
        accessibility: "Доступность",
        fontSize: "Размер шрифта",
        highContrast: "Высокая контрастность",
        setting1: "Настройка 1",
        setting2: "Настройка 2",
        setting3: "Настройка 3",
        changePassword: "Сменить пароль",
        myReservations: "Мои бронирования",
        save: "Сохранить изменения",
        loyality_points: "Текущие баллы лояльности",
        fav_meals: "Свободные места для избранных блюд",
        loyality_discount: "Максимальная скидка по баллам лояльности",
        loyality_level: "Уровень лояльности",
    },
    changePassword: {
      title: 'Сменить пароль',
      old: 'Старый пароль',
      new: 'Новый пароль',
      confirm: 'Подтвердите новый пароль',
      save: 'Сменить пароль',
      success: 'Пароль успешно изменен.',
      errorMismatch: 'Новые пароли не совпадают.',
      errorEmpty: 'Пожалуйста, заполните все поля.',
      errorAnon: 'Анонимные пользователи не могут менять пароль.',
      errorServer: 'Ошибка подключения к серверу.',
      errorUnknown: 'Не удалось изменить пароль.',
      saving: 'Сохраняем...',
    },
    MainMenu:{
      today_special: "Специальное предложение на сегодня",
      categories: "Категории",
      your_space: "Ваше пространство",
      menu: "Меню",
      search: "Поиск",
      admin_only: "Только для администраторов",
      unauthorized: "Несанкционированный доступ"
    },
    DeliveryScreen: {
      delivery: "Доставка",
      reservetion: "Резервирование",
      street: "Улица",
      postal_code: "Почтовый индекс",
      reservation: "Резервирование",
      number: " Номер",
      order_now: "Заказать сейчас",
      comment: "Комментарий",
      date: "Выберите дату",
      time_from: "время с",
      time_to: "время до",
      pay: "Оплатить",
      number_of_people: "Количество гостей",
      address: "Адрес доставки",
      change_address: "Изменить адрес",
      delivery_options: "Возможность доставки или резервирования",
      contactless: "Бесконтактная доставка",
      leave_at_door: "Оставить у двери",
      instructions: "Инструкции по доставке",
      confirm: "Подтвердить доставку",
      cancel: "Отменить заказ",
      status_preparing: "Ваш заказ готовится...",
      status_out_for_delivery: "Заказ в пути",
      status_delivered: "Доставлено",
      error_invalid_address: "Пожалуйста, введите корректный адрес.",
      error_no_connection: "Нет подключения. Попробуйте снова.",
      success_confirmed: "Ваша доставка подтверждена.",
      success_cancelled: "Ваша доставка отменена."
    },
    LoyalityScreen: {
      title: "Программа лояльности",
      points: "Очки",
      rewards: "Награды",
      discount: "Скидка",
      currentDiscount: "Текущая скидка",
      skipButton: "Пропустить",
      loading: "The incorrect data read. Try again after account verification."
  
    },
    RegisterScreen: {
      register: "Зарегистрироваться",
      password_again: "Повторите пароль",
    },
      AddItemScreen:  {
      dish_title: "Название блюда:",
      dish_image: "Предмет блюда:",
      category: "Категория:",
      description: "Описание:",
      portion_size: "Размер порции:",
      unit: "Единица порции:",
      discount: "База скидок:",
      special: "Today's Special:",
      cancel: "Отмена",
      addButton: "Добавить товар",
      small: "Маленький",
      medium: "Средний",
      large: "Большой",
      delete: "Удалить",
      save: "Сохранить",
      unit2: "Единица измерения (г/мл):",
      discount2: "Скидка %:",
      size: "Размер:",
      price: "Цена:",
      error: "Ошибка",
      category2: "Введите категорию",
      title2: "Введите название блюда",
      desc2: "Введите описание",
      unit3: "Введите единицу порции (г/мл)",
      },
      FavouriteMealsScreen: { 
        title: "Избранные блюда",
        },
      
      PaymentScreen: {
        title: "Оплата",
        cash: "Наличные",
        with_card: "Оплатить картой",
        after_delivery: "Оплатить после доставки",
        card: "Детали карты",
        card_number: "Номер карты",
        card_expiry: "Срок действия карты",
        card_cvc: "CVC",
        number_of_items: "Количество предметов",
        total_price: "Общая цена",
        discount: "Скидка",
        total: "Итого",
        pay: "Оплатить",
        confirm: "Подтвердить", 
        delivery_price: "Цена доставки: 2.50 €",
        reservation_price: "Цена резервирования: 1.50 €",
      },
      add_to_cart: "Добавить в корзину",

      ShoppingCartScreen: {
        title: "Корзина",
        empty: "Ваша корзина пуста",
        total_price: "Общая цена",
        total_items: "Всего предметов",
        remove_item: "Удалить предмет",
        checkout: "Оформить заказ",
        continue_shopping: "Продолжить покупки",
        item_count: "Количество предметов",
        item_price: "Цена предмета",
        order: "Заказать",
      },
  };