export default {
    login: {
      title: 'Логин',
      anonymous: 'Анонимный режим',
      register: 'Регистрация',
    },
    account: {
        pubName: "У слепого орла",
        login: "Войти",
        register: "Зарегистрироваться",
        anonymous: "Анонимный режим",
        discount: "Скидка",
        logout: "Выйти",
        darkMode: "Тёмный режим",
        language: "Язык",
        accessibility: "Доступность",
        fontSize: "Размер шрифта",
        highContrast: "Высокая контрастность",
        setting1: "Настройка 1",
        setting2: "Настройка 2",
        setting3: "Настройка 3",
        changePassword: "Сменить пароль",
        myReservations: "Мои бронирования",
        save: "Сохранить изменения"
    },
    changePassword: {
      title: 'Сменить пароль',
      old: 'Старый пароль',
      new: 'Новый пароль',
      confirm: 'Подтвердите новый пароль',
      save: 'Сменить пароль',
      success: 'Пароль успешно изменен.',
      errorMismatch: 'Новые пароли не совпадают.',
      errorEmpty: 'Пожалуйста, заполните все поля.',
      errorAnon: 'Анонимные пользователи не могут менять пароль.',
      errorServer: 'Ошибка подключения к серверу.',
      errorUnknown: 'Не удалось изменить пароль.',
      saving: 'Сохраняем...',
    },
    MainMenu:{
      today_special: "Специальное предложение на сегодня",
      categories: "Категории",
      your_space: "Ваше пространство",
      menu: "Меню",
      search: "Поиск",
      admin_only: "Только для администраторов",
      unauthorized: "Несанкционированный доступ"
    },
    DeliveryScreen: {
      title: "Доставка",
      order_now: "Заказать сейчас",
      track_order: "Отслеживать заказ",
      delivery_time: "Предполагаемое время доставки",
      address: "Адрес доставки",
      change_address: "Изменить адрес",
      delivery_options: "Параметры доставки",
      contactless: "Бесконтактная доставка",
      leave_at_door: "Оставить у двери",
      instructions: "Инструкции по доставке",
      confirm: "Подтвердить доставку",
      cancel: "Отменить заказ",
      status_preparing: "Ваш заказ готовится...",
      status_out_for_delivery: "Заказ в пути",
      status_delivered: "Доставлено",
      error_invalid_address: "Пожалуйста, введите корректный адрес.",
      error_no_connection: "Нет подключения. Попробуйте снова.",
      success_confirmed: "Ваша доставка подтверждена.",
      success_cancelled: "Ваша доставка отменена."
    }
  };