import FavouriteMealsScreen from "../screens/favourites";
import RegisterScreen from "../screens/register";
import ShoppingCartScreen from "../screens/shopping_cart";

export default {
    login: {
    appName: 'U slepého orla',
    name: 'Meno',
    password: 'Heslo',
    rememberMe: 'Zapamätať si ma',
    loginButton: 'Prihlásiť sa',
    loginFailed: 'Prihlásenie zlyhalo',
    connectionFailed: 'Chyba pripojenia',
    offlineModeMessage: 'Používa sa offline režim...'
    },
    account: {
        pubName: "U slepého orla",
        login: "Prihlásiť sa",
        register: "Zaregistrovať sa",
        anonymous: "Anonymný režim",
        discount: "Zľava",
        logout: "Odhlásiť sa",
        darkMode: "Tmavý režim",
        language: "Jazyk",
        accessibility: "Prístupnosť",
        fontSize: "Veľkosť písma",
        highContrast: "Vysoký kontrast",
        setting1: "Nastavenie 1",
        setting2: "Nastavenie 2",
        setting3: "Nastavenie 3",
        changePassword: "Zmeniť heslo",
        myReservations: "Moje rezervácie",
        save: "Uložiť zmeny",
        loyality_points: "Aktuálne vernostné body",
        fav_meals: "Voľné miesta pre obľúbené jedlá",
        loyality_discount: "Maximálna zľava z vernostných bodov",
        loyality_level: "Úroveň vernosti",
    },
    changePassword: {
      title: 'Zmeniť heslo',
      old: 'Staré heslo',
      new: 'Nové heslo',
      confirm: 'Potvrďte nové heslo',
      save: 'Zmeniť heslo',
      success: 'Heslo bolo úspešne zmenené.',
      errorMismatch: 'Nové heslá sa nezhodujú.',
      errorEmpty: 'Vyplňte všetky požadované polia.',
      errorAnon: 'Anonymní používatelia nemôžu meniť heslo.',
      errorServer: 'Nepodarilo sa pripojiť k serveru.',
      errorUnknown: 'Nepodarilo sa zmeniť heslo.',
      saving: 'Ukladá sa...',
    },
    MainMenu:{
      today_special: "Špeciálna ponuka",
      categories: "Kategórie",
      your_space: "Tvoj priestor",
      menu: "Menu",
      search: "Hľadať",
      admin_only: "Len pre administrátorov",
      unauthorized: "Neoprávnený prístup"
    },
    DeliveryScreen: {
      delivery: "Doručenie",
      reservetion: "Rezervácia",
      street: "Ulica",
      postal_code: "PSČ",
      reservation: "Rezervácia",
      number: "Číslo",
      order_now: "Order Now",
      comment: "Komentár",
      date: "Vyberte dátum",
      time_from: "čas od",
      time_to: "čas do",
      pay: "Zaplaťte",
      number_of_people: "Počet hostí",
      track_order: "Sledovať objednávku",
      delivery_time: "Odhadovaný čas doručenia",
      address: "Adresa doručenia",
      change_address: "Zmeniť adresu",
      delivery_options: "Možnosti doručenia alebo rezervácie",
      contactless: "Bezkontaktné doručenie",
      leave_at_door: "Nechať pri dverách",
      instructions: "Pokyny pre doručenie",
      confirm: "Potvrdiť doručenie",
      cancel: "Zrušiť objednávku",
      status_preparing: "Pripravujeme vašu objednávku...",
      status_out_for_delivery: "Na ceste k vám",
      status_delivered: "Doručené",
      error_invalid_address: "Zadajte platnú adresu.",
      error_no_connection: "Bez pripojenia. Skúste znova.",
      success_confirmed: "Vaše doručenie bolo potvrdené.",
      success_cancelled: "Vaše doručenie bolo zrušené."
    },
    LoyalityScreen: {
      title: "Vernostný program",
      points: "Body",
      rewards: "Odmeny",
      discount: "Zľava",
      currentDiscount: "Aktuálna zľava",
      skipButton: "Preskočiť"
    },
    RegisterScreen: {
      register: "Zaregistrovať sa",
      password_again: "Heslo znova"
    },
    AddItemScreen:  {
        dish_title: "Názov jedla:",
        dish_image: "Dish Item:",
        category: "Kategória:",
        description: "Description:",
        portion_size: "Veľkosť porcie:",
        unit: "Portion Unit:",
        discount: "Základná zľava:",
        special: "Dnešná zľava:",
        cancel: "Zrušiť",
        addButton: "Add item",
        small: "Small",
        medium: "Medium",
        large: "Large",
        delete: "Delete",
        save: "Uložiť",
        unit2: "Jednotka (g/ml):",
        discount2: "Zľava %:",
        size: "Veľkosť:",
        price: "Cena:",
        error: "Chyba",
        category2: "Zadajte kategóriu",
        title2: "Zadajte názov pokrmu",
        desc2: "Zadajte opis",
        unit3: "Zadajte jednotku porcie (g/ml)",
      },

    FavouriteMealsScreen: {
      title: "Obľúbené jedlá",
    },

    PaymentScreen: {     
      názov: "Payment",
      with_card: "Zaplatiť kartou",
      after_delivery: "Zaplatiť po doručení",
      card: "Údaje o karte",
      card_number: "Číslo karty",
      card_expiry: "Dátum platnosti (MM/RRRR)",
      card_cvc: "CVC",
      number_of_items: "Počet položiek",
      total_price: "Celková cena",
      discount: "Zľava",
      pay: "Pay",
      confirm: "Vaše potvrdenie:",
      total: "Total",
      delivery_price: "Delivery: 2.50 €",
      reservation_price: "Rezervácia: 1.50 €",

    },
    add_to_cart: "Pridať do košíka",

    ShoppingCartScreen: {
      title: "Nákupný košík",
      empty: "Košík je prázdny",
      total_price: "Celková cena",
      total_items: "Celkový počet položiek",
      checkout: "Pokladňa",
      remove_item: "Odstrániť položku",
      update_quantity: "Aktualizovať množstvo",
      item_details: "Podrobnosti o položke",
      item_name: "Názov položky",
      item_size: "Veľkosť položky",
      order: "Objednať",
    },
};