import RegisterScreen from "../screens/register";

export default {
    login: {
    appName: 'U slepého orla',
    name: 'Meno',
    password: 'Heslo',
    rememberMe: 'Zapamätať si ma',
    loginButton: 'Prihlásiť sa',
    loginFailed: 'Prihlásenie zlyhalo',
    connectionFailed: 'Chyba pripojenia',
    offlineModeMessage: 'Používa sa offline režim...'
    },
    account: {
        pubName: "U slepého orla",
        login: "Prihlásiť sa",
        register: "Zaregistrovať sa",
        anonymous: "Anonymný režim",
        discount: "Zľava",
        logout: "Odhlásiť sa",
        darkMode: "Tmavý režim",
        language: "Jazyk",
        accessibility: "Prístupnosť",
        fontSize: "Veľkosť písma",
        highContrast: "Vysoký kontrast",
        setting1: "Nastavenie 1",
        setting2: "Nastavenie 2",
        setting3: "Nastavenie 3",
        changePassword: "Zmeniť heslo",
        myReservations: "Moje rezervácie",
        save: "Uložiť zmeny"
    },
    changePassword: {
      title: 'Zmeniť heslo',
      old: 'Staré heslo',
      new: 'Nové heslo',
      confirm: 'Potvrďte nové heslo',
      save: 'Zmeniť heslo',
      success: 'Heslo bolo úspešne zmenené.',
      errorMismatch: 'Nové heslá sa nezhodujú.',
      errorEmpty: 'Vyplňte všetky požadované polia.',
      errorAnon: 'Anonymní používatelia nemôžu meniť heslo.',
      errorServer: 'Nepodarilo sa pripojiť k serveru.',
      errorUnknown: 'Nepodarilo sa zmeniť heslo.',
      saving: 'Ukladá sa...',
    },
    MainMenu:{
      today_special: "Špeciálna ponuka",
      categories: "Kategórie",
      your_space: "Tvoj priestor",
      menu: "Menu",
      search: "Hľadať",
      admin_only: "Len pre administrátorov",
      unauthorized: "Neoprávnený prístup"
    },
    DeliveryScreen: {
      delivery: "Doručenie",
      reservetion: "Rezervácia",
      street: "Ulica",
      postal_code: "PSČ",
      reservation: "Rezervácia",
      number: "Číslo",
      order_now: "Order Now",
      comment: "Komentár",
      date: "Vyberte dátum",
      time_from: "čas od",
      time_to: "čas do",
      pay: "Zaplaťte",
      number_of_people: "Počet hostí",
      track_order: "Sledovať objednávku",
      delivery_time: "Odhadovaný čas doručenia",
      address: "Adresa doručenia",
      change_address: "Zmeniť adresu",
      delivery_options: "Možnosti doručenia alebo rezervácie",
      contactless: "Bezkontaktné doručenie",
      leave_at_door: "Nechať pri dverách",
      instructions: "Pokyny pre doručenie",
      confirm: "Potvrdiť doručenie",
      cancel: "Zrušiť objednávku",
      status_preparing: "Pripravujeme vašu objednávku...",
      status_out_for_delivery: "Na ceste k vám",
      status_delivered: "Doručené",
      error_invalid_address: "Zadajte platnú adresu.",
      error_no_connection: "Bez pripojenia. Skúste znova.",
      success_confirmed: "Vaše doručenie bolo potvrdené.",
      success_cancelled: "Vaše doručenie bolo zrušené."
    },
    LoyalityScreen: {
      title: "Vernostný program",
      points: "Body",
      rewards: "Odmeny",
      discount: "Zľava",
      currentDiscount: "Aktuálna zľava",
      loginButton: "Prihlásiť sa"
    },
    RegisterScreen: {
      register: "Zaregistrovať sa",
      password_again: "Heslo znova"
    },
  };